name: Deploy PWA Starter to GitHub Pages

on:
  workflow_dispatch:
  
jobs:
  build:
    defaults:
      run:
        working-directory: app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Vite Build
        run: pnpm run build -- --base=${{ github.event.repository.name }}
        
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./app/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
